###
GET https://thequizzapi.sem2.dk/api/auth/test

###
POST https://thequizzapi.sem2.dk/api/auth/register
Content-Type: application/json

{
  "username": "Jim4",
  "password": "1234"
}
###
POST https://thequizzapi.sem2.dk/api/auth/login
Content-Type: application/json

{
"username": "Jim2",
"password": "1234"
}
###
POST https://thequizzapi.sem2.dk/api/auth/login
Content-Type: application/json

{
  "username": "PineBoxJim",
  "password": "4321"
}
> {%
    client.global.set("token", response.body.token);
%}

###
GET https://thequizzapi.sem2.dk/api/admin/populate
Authorization: Bearer {{token}}

###
POST https://thequizzapi.sem2.dk/api/game/2
Authorization: Bearer {{token}}
Content-Type: application/json

###
POST https://thequizzapi.sem2.dk/api/game/1/players/names
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "players": [
    {"name": "Player1", "points": 0},
    {"name": "Player2", "points": 0}
  ]
}
###
POST https://thequizzapi.sem2.dk/api/game/1/questions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "limit": 10,
  "category": "Science: Computers",
  "difficulty": "EASY"
}

###
GET https://thequizzapi.sem2.dk/api/game/1/score
Authorization: Bearer {{token}}
