###
GET http://localhost:7070/api/auth/test

###
POST http://localhost:7070/api/auth/register
Content-Type: application/json

{
  "username": "Jim",
  "password": "1234"
}
###
POST http://localhost:7070/api/auth/login
Content-Type: application/json

{
  "username": "Jim",
  "password": "1234"
}
> {%
    client.global.set("token", response.body.token);
%}
###

POST http://localhost:7070/api/auth/login
Content-Type: application/json

{
  "username": "PineBoxJim",
  "password": "4321"
}
> {%
    client.global.set("token", response.body.token);
%}

###
GET http://localhost:7070/api/admin/populate
Authorization: Bearer {{token}}

###
POST http://localhost:7070/api/game/2
Authorization: Bearer {{token}}
Content-Type: application/json

###
POST http://localhost:7070/api/game/1/players/names
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "players": [
    {"name": "Player1Game2", "points": 0},
    {"name": "Player2Game2", "points": 0}
  ]
}
###
POST http://localhost:7070/api/game/5/questions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "limit": 10,
  "category": "Science: Computers",
  "difficulty": "EASY",
  "gameMode": "TURN"
}

###
POST http://localhost:7070/api/game/savegame/5/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "players": {
    "players": [
      {
        "name": "Player1Game2",
        "points": 1
      },
      {
        "name": "Player2Game2",
        "points": 2
      }
    ]
  },
  "questions": {
    "results": [
      {
        "difficulty": "EASY",
        "category": "Science: Computers",
        "question": "A Mac is not a PC",
        "correct_answer": "False",
        "incorrect_answers": [
          "True"
        ]
      },
      {
        "difficulty": "EASY",
        "category": "Science: Computers",
        "question": "Which programming language shares its name with an island in Indonesia?",
        "correct_answer": "Java",
        "incorrect_answers": [
          "Python",
          "C",
          "Jakarta"
        ]
      },
      {
        "difficulty": "EASY",
        "category": "Science: Computers",
        "question": "The logo for Snapchat is a Bell.",
        "correct_answer": "False",
        "incorrect_answers": [
          "True"
        ]
      },
      {
        "difficulty": "EASY",
        "category": "Science: Computers",
        "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
        "correct_answer": "True",
        "incorrect_answers": [
          "False"
        ]
      },
      {
        "difficulty": "EASY",
        "category": "Science: Computers",
        "question": "What programming language was GitHub written in?",
        "correct_answer": "Ruby",
        "incorrect_answers": [
          "JavaScript",
          "Python",
          "Lua"
        ]
      },
      {
        "difficulty": "EASY",
        "category": "Science: Computers",
        "question": "Time on Computers is measured via the EPOX System.",
        "correct_answer": "False",
        "incorrect_answers": [
          "True"
        ]
      },
      {
        "difficulty": "EASY",
        "category": "Science: Computers",
        "question": "What is the domain name for the country Tuvalu?",
        "correct_answer": ".tv",
        "incorrect_answers": [
          ".tu",
          ".tt",
          ".tl"
        ]
      },
      {
        "difficulty": "EASY",
        "category": "Science: Computers",
        "question": "In any programming language, what is the most common way to iterate through an array?",
        "correct_answer": "&#039;For&#039; loops",
        "incorrect_answers": [
          "&#039;If&#039; Statements",
          "&#039;Do-while&#039; loops",
          "&#039;While&#039; loops"
        ]
      },
      {
        "difficulty": "EASY",
        "category": "Science: Computers",
        "question": "What is the name of Layer 7 of the OSI model?",
        "correct_answer": "Application",
        "incorrect_answers": [
          "Session",
          "Network",
          "Present"
        ]
      },
      {
        "difficulty": "EASY",
        "category": "Science: Computers",
        "question": "What amount of bits commonly equals one byte?",
        "correct_answer": "8",
        "incorrect_answers": [
          "1",
          "2",
          "64"
        ]
      }
    ]
  },
  "turn": 3
}